#!/usr/bin/env python3

from gpiozero import DistanceSensor
from gpiozero.pins.pigpio import PiGPIOFactory

import time

factory = PiGPIOFactory(host="localhost")
sensor = DistanceSensor(trigger=23, echo=24, pin_factory=factory)

if __name__ == "__main__":
    print("Reading distance")
    sum = 0.0
    for _ in range(500):
        sum = sum + sensor.distance
        time.sleep(0.1)
    sum = sum / 500
    print(f"Distance: {round(sum * 100, 1)}cm")
