#!/usr/bin/env python3

from gpiozero import DistanceSensor
from gpiozero.pins.pigpio import PiGPIOFactory

import time
import yaml
import sys

def load_config():
    with open("config.yml", "r") as file:
        return(yaml.safe_load(file))

if __name__ == "__main__":
    config = load_config()
    factory = PiGPIOFactory(host="localhost")
    sensor_config = config[sys.argv[1]]
    sensor = DistanceSensor(
        trigger=sensor_config["trigger"],
        echo=sensor_config["echo"],
        pin_factory=factory
    )
    time.sleep(0.25)
    print(f"Distance: {round(sensor.distance * 100, 1)}cm")
    time.sleep(0.25)
